blank_issues_enabled: false
contact_links:
    - name: Ask a question
      url: https://github.com/Ladsers
      about: Please ask and answer questions here
    - name: Suggest an idea
      url: https://github.com/Ladsers
      about: Suggest an idea for this app
